# Generated by Django 3.2 on 2022-11-06 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('user_name', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(default='123456', max_length=255)),
                ('user_auth', models.CharField(default='user', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user',
                'managed': (True,),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('task_description', models.CharField(max_length=255, null=True)),
                ('task_config', models.CharField(max_length=255)),
                ('task_status', models.CharField(max_length=255)),
                ('task_status_description', models.CharField(default='', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_create_user', to='aim.user')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_update_user', to='aim.user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aim.user')),
            ],
            options={
                'db_table': 'task',
                'managed': (True,),
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('dataset_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('dataset_name', models.CharField(max_length=255)),
                ('dataset_description', models.CharField(max_length=255, null=True)),
                ('dataset_filename', models.CharField(max_length=255)),
                ('dataset_size', models.IntegerField()),
                ('dataset_num', models.IntegerField()),
                ('dataset_type', models.CharField(default='images', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_create_user', to='aim.user')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dataset_update_user', to='aim.user')),
            ],
            options={
                'db_table': 'dataset',
                'managed': (True,),
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('config_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('config_name', models.CharField(max_length=255)),
                ('config_description', models.CharField(max_length=255, null=True)),
                ('config_content', models.CharField(max_length=255)),
                ('config_type', models.CharField(default='interpreter', max_length=255)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_create_user', to='aim.user')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_update_user', to='aim.user')),
            ],
            options={
                'db_table': 'configuration',
                'managed': (True,),
            },
        ),
    ]
