# Generated by Django 3.2 on 2022-11-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aim', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='username',
        ),
    ]
