# Generated by Django 3.2 on 2022-11-07 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aim', '0003_auto_20221107_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_name',
            field=models.CharField(default='asd', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='configuration',
            name='config_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='dataset_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
