# Generated by Django 3.2 on 2022-11-08 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aim', '0005_alter_dataset_dataset_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepModel',
            fields=[
                ('model_id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(max_length=255)),
                ('model_description', models.CharField(max_length=255, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('create_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_create_user', to='aim.user')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_update_user', to='aim.user')),
            ],
            options={
                'db_table': 'model',
                'managed': (True,),
            },
        ),
    ]
