# Generated by Django 3.2 on 2022-11-08 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aim', '0006_deepmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepmodel',
            name='model_filename',
            field=models.CharField(default='un', max_length=255),
            preserve_default=False,
        ),
    ]
