# Generated by Django 3.2 on 2022-11-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aim', '0007_deepmodel_model_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepmodel',
            name='model_classname',
            field=models.CharField(default='asd', max_length=255),
            preserve_default=False,
        ),
    ]
