# Generated by Django 3.2 on 2022-11-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aim', '0008_deepmodel_model_classname'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepmodel',
            name='model_output_shape',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deepmodel',
            name='model_size',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
