# Generated by Django 3.2 on 2022-11-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aim', '0009_auto_20221108_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepmodel',
            name='model_type',
            field=models.CharField(default='LeNet', max_length=255),
        ),
    ]
