# Generated by Django 3.2.16 on 2022-11-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aim', '0012_deepmodel_model_dataset'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepmodel',
            name='is_predefine',
            field=models.BooleanField(default=False),
        ),
    ]
