# Generated by Django 3.2.16 on 2022-11-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aim', '0013_deepmodel_is_predefine'),
    ]

    operations = [
        migrations.AddField(
            model_name='deepmodel',
            name='is_use_function',
            field=models.BooleanField(default=False),
        ),
    ]
